version: '3.8'

services:
  taskmanager-server:
    build: ./server
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  taskmanager-client:
    build: ./client
    depends_on:
      - taskmanager-server
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831

  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  jaeger:
    image: jaegertracing/all-in-one:1.28
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"